export const timelineData = [
  // Educación
  {
    id: 1,
    type: "education",
    title: "Ingeniería de Sistemas",
    subtitle: "Ingeniero de Sistemas",
    place: "Universidad César Vallejo",
    date: "Set 2021 - Jul 2024",
    startDate: "2021-09-01",
    endDate: "2024-07-21",
  },
  // {
  //   id: 2,
  //   type: "education",
  //   title: "Cursos de Programación",
  //   subtitle: "Programación Backend",
  //   place: "ONE - Oracle Next Education",
  //   date: "Abr 2023 - Dic 2023",
  //   startDate: "2023-04-01",
  //   endDate: "2023-12-01",
  // },
  {
    id: 3,
    type: "education",
    title: "Ingeniería de Minas",
    subtitle: "Bachiller en Ingeniería de Minas",
    place: "Universidad Nacional de Trujillo",
    date: "Abr 2014 - Dic 2018",
    startDate: "2014-04-01",
    endDate: "2018-12-15",
  },

  // Experiencia
  {
    id: 4,
    type: "experience",
    title: "Programador de Sistemas Informáticos",
    subtitle: "Subgerencia de Informática y Sistemas",
    place: "Municipalidad Distrital de La Esperanza",
    date: "Oct 2024 - Actualidad",
    startDate: "2024-10-01",
    endDate: null,
  },
  {
    id: 5,
    type: "experience",
    title: "Locador de Soporte Técnico",
    subtitle: "Subgerencia de Informática y Sistemas",
    place: "Municipalidad Distrital de La Esperanza",
    date: "Feb 2024 - Set 2024",
    startDate: "2024-02-14",
    endDate: "2024-09-01",
  },
  {
    id: 6,
    type: "experience",
    title: "Practicante de Sistemas",
    subtitle: "Subgerencia de Informática y Sistemas",
    place: "Municipalidad Distrital de La Esperanza",
    date: "Feb 2023 - Dic 2023",
    startDate: "2023-02-14",
    endDate: "2023-12-11",
  },
  {
    id: 7,
    type: "experience",
    title: "Supervisor de Operaciones",
    subtitle: "Corporación e Inversiones Piscis",
    place: "Cía. Minera SummaGold S.A.C.",
    date: "Ene 2021 - Dic 2021",
    startDate: "2021-01-01",
    endDate: "2021-12-01",
  },
  {
    id: 8,
    type: "education",
    title: "Java Developer",
    subtitle: "Curso de Programación Java",
    place: "CJAVA",
    date: "Oct 2025 - Nov 2025",
    startDate: "2025-10-01",
    endDate: "2025-11-18",
  },
  {
    id: 9,
    type: "experience",
    title: "Viña Cascas",
    subtitle: "Desarrollo freelance",
    place: "Trujillo",
    date: "Dic 2025 - Actualidad",
    startDate: "2025-12-12",
    endDate: null,
  },
  {
    id: 10,
    type: "education",
    title: "Java Expert",
    subtitle: "Curso de Programación Java",
    place: "CJAVA",
    date: "Nov 2025 - Ene 2026",
    startDate: "2025-11-01",
    endDate: "2026-01-25",
  },
];